const ListaMongo = require("../models/ListaMongo");
const mongoose = require("mongoose");

const productseng = {
    Pantry: [
    "chocolate milk",
    "Sugar",
    "sweetener",
    "Rice",
    "Canned Tuna",
    "Olive oil",
    "Olive",
    "potato sticks",
    "vanilla",
    "Cookies",
    "Candy",
    "Coffee",
    "Broth",
    "Catchup",
    "Cereal",
    "Tea",
    "Champignon",
    "Chocolate",
    "Granulated Chocolate",
    "Grated Coconut",
    "Milk Cream",
    "Cassava flour",
    "Cornflour",
    "Breadcrumbs",
    "Wheat flour",
    "Bean",
    "Yeast",
    "Gelatine",
    "Jelly",
    "Milk",
    "Condensed milk",
    "Coconut milk",
    "Lentil",
    "Spaghetti",
    "Mayonnaise",
    "Sauce",
    "Mustard",
    "Tomato paste",
    "Polvilho",
    "Sago",
    "Salt",
    "Coarse salt",
    "Sausage",
    "Sardine",
    "Soup",
    "Seasoning",
    "Water",
    "Coconut water",
    "Tonic water",
    "Beer",
    "Champagne",
    "Liquor",
    "Soda",
    "Rum",
    "Juice",
    "Wine",
    "Vodka",
    "Whiskey",
    "Milk",
    "Cookies",
    "Cakes",
    "Sweets",
    "Breads",
    "Salty",
    "Pies",
    "Phosphor",
    "Candles",
    "Stacks",
    "Coal",
    "Cassava flour",
    "Cornflour",
    "Breadcrumbs",
    "Wheat flour",
    "Bean",
    "Yeast",
    "Gelatine",
    "Jelly",
    "Milk",
    "Condensed milk",
    "Coconut milk",
    "Lentil",
    "Spaghetti",
    "Mayonnaise",
    "Sauce",
    "Mustard",
    "Tomato paste",
    "Polvilho",
    "Sago",
    "Salt",
    "Coarse salt",
    "Sausage",
    "Sardine",
    "Soup",
    "Seasoning",
    "Water",
    "Coconut water",
    "Tonic water",
    "Beer",
    "Champagne",
    "Liquor",
    "Soda",
    "Rum",
    "Juice",
    "Wine",
    "Vodka",
    "Whiskey",
    "Milk",
    "Cookies",
    "Cakes",
    "Sweets",
    "Breads",
    "Salty",
    "Pies",
    "Phosphor",
    "Candles",
    "Battery",
    "Coal",
  ],
  Freezer: [
    "Beef",
    "Chicken",
    "Fish",
    "Pig",
    "Ice cream",
    "Hamburger",
    "Pizza",
  ],
  Refrigerator: [
    "Bacon",
    "Chester",
    "Yogurt",
    "Sausage",
    "Butter",
    "Margarine",
    "Mortadela",
    "Cream",
    "Pate",
    "Turkey breast",
    "Ham",
    "Cheese",
    "Grated cheese",
    "Creamy cheese",
    "Ricotta",
    "Salami",
    "Eggs",
  ],
  "Fruits and Vegetables": [
    "Avocado",
    "Pineapple",
    "Zucchini",
    "Cress",
    "Lettuce",
    "Garlic",
    "Banana",
    "Potato",
    "Eggplant",
    "Beet",
    "Broccoli",
    "Onion",
    "Carrot",
    "Chuchu",
    "Cabbage",
    "Spinach",
    "Guava",
    "Orange",
    "Apple",
    "Papaya",
    "Basil",
    "Watermelon",
    "Melon",
    "Wait",
    "Bell pepper",
    "Cabbage",
    "Arugula",
    "Parsley",
    "Green spice",
    "Tomato",
    "Grape",
    "Pod",
    "Pod",
    "Pea",
    "Heart of palm",
    "Corn",
    "Cucumber",
    "Chard",
  ],
  Hygiene: [
    "Tampons",
    "Acetone",
    "Cotton",
    "Mouthwash",
    "Conditioner",
    "Nail clippers",
    "Swab",
    "Shaving cream",
    "Deodorant",
    "Toothbrush",
    "Enamel",
    "Floss",
    "Fixer",
    "Diapers",
    "Gel",
    "Moisturizer",
    "Razor blade",
    "Tissue",
    "Sandpaper",
    "Comb",
    "Tweezers",
    "Condom",
    "Soap",
    "Shampoo",
    "Baby powder",
    "Sanitary water",
    "Alcohol",
    "Bleach",
    "Softener",
    "Disinfectant",
    "Detergent",
    "Sponge",
    "Napkin",
    "Insecticide",
    "Wash clothes",
    "Glass cleaner",
    "Furniture polish",
    "Toothpick",
    "Cleaning cloth",
    "Dishcloth",
    "Toilet paper",
    "Environment Purifier",
    "Washing powder",
    "Garbage bag",
    "Paper towel",
    "Broom",
  ],
};

/* mongoose
  .connect("mongodb://localhost/Proj3-Database", {
    useCreateIndex: true,
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then((x) => {
    console.log(
      `Connected to Mongo! Database name: "${x.connections[0].name}"`
    );
  })
  .then(() => {
    ListaMongo.insertMany(products)
      .then((result) => console.log("Populated database!", result))
      .catch((err) => console.error(err));
  })
  .catch((err) => {
    console.error("Error connecting to mongo", err);
  });
 */
